services:
  nightfall:
    build: .
    image: nightfall:latest
    container_name: chronos_challenge_nightfall
    ports:
      - "9001:80"
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    pids_limit: 100
