services:
  configgate:
    build: .
    container_name: chronos_challenge_configgate
    ports:
      - "9000:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    pids_limit: 100
