services:
  inyeccion-clasica:
    build: .
    image: inyeccion-clasica:latest
    container_name: chronos_challenge_inyeccion_clasica
    ports:
      - "8009:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    pids_limit: 50
