services:
  ruta-prohibida:
    build: .
    container_name: chronos_challenge_ruta_prohibida
    ports:
      - "8010:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    pids_limit: 50
